NDefines.NDiplomacy.BASE_REVOLT_CHANCE_MOD = 125
NDefines.NDiplomacy.TOG_REVOLT_CHANCE_MOD = 50

NDefines.NCharacter.PORTRAIT_MID_AGE_THRESHOLD = 55
NDefines.NCharacter.PORTRAIT_OLD_AGE_THRESHOLD = 120
NDefines.NCharacter.MAX_CHILD_BIRTH_AGE = 12000
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_STANDARD = 0.05

NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 1
NDefines.NTechnology.POINTS_PER_ATTRIBUTE = 0.00
NDefines.NTechnology.BASE_NEIGHBOUR_SPREAD_BONUS = 0.00
NDefines.NTechnology.NEIGHBOUR_SAME_RELIGON_GROUP_MULT = 2.0
NDefines.NTechnology.BASE_DEMESNE_SPREAD_BONUS = 0.00
NDefines.NTechnology.MAX_DEMESNE_BONUS = 0.0
NDefines.NTechnology.TRADEPOST_SPREAD_BONUS = 0.000
NDefines.NTechnology.SPYACTION_SPREAD_BONUS = 0.000
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 1
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 16000

NDefines.NTitle.ENFORCE_ONE_OF_EACH_HOLDING = 0